<?php

namespace StockBundle\Repository;

use UserBundle\Entity\FosUser;

/**
 * StockCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockCategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function listeCategorieSoc($userID = null )
    {
        $societe = $this->_em->getRepository(FosUser::class)->find($userID)->getAgence()->getSociete();

        return $this
            ->createQueryBuilder('a')
            ->where('a.societe = :societe')
            ->setParameter('societe', $societe);
    }
}
