<?php

namespace StockBundle\Repository;

/**
 * StockApprovisionnementDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockApprovisionnementDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
