<?php

namespace StockBundle\Repository;

/**
 * StockArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockArtRepository extends \Doctrine\ORM\EntityRepository
{
}
