<?php

namespace StockBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Symfony\Component\Validator\Constraints\Count;
use UserBundle\Entity\FosUser;

/**
 * StockArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function taille($societe)
    {
        $tab = $this->_em->createQuery(
            "select count(a)
            from StockBundle:StockArticle a
            inner join ConfigBundle:ConfigSociete s with s = a.societe
            where s = :soc"
        )
            ->setParameter('soc', $societe)
            ->getResult();
        return $tab[0][1];
    }

    public function listeArticleSoc($userID = null )
    {
        $societe = $this->_em->getRepository(FosUser::class)->find($userID)->getAgence()->getSociete();

        return $this
            ->createQueryBuilder('a')
            ->where('a.societe = :societe')
            ->setParameter('societe', $societe);
    }
}
