<?php

namespace StockBundle\Repository;

/**
 * StockInventaireDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockInventaireDetailRepository extends \Doctrine\ORM\EntityRepository
{

/*
 *  A faire, récuperer la liste de tout les détails liés à une société
 *
    public function listClient(ConfigSociete $societe) {
        return $this->_em->createQuery(
            "select t.id, t.nom, p.TauxTva tva
            from TiersBundle:TiersTiers t
            inner join TiersBundle:TiersClient c with c = t
            inner join ConfigBundle:ConfigPays p with p = t.pays
            where t.societe = :societe
            and t.estSupprimer = 0"
        )->setParameter('societe', $societe)
            ->getResult();
    }*/

    public function liste($societe)
    {
        $tab = $this->_em->createQuery(
            "select a
            from StockBundle:StockInventaireDetail a
            inner join StockBundle:StockArticle r with r = a.article
            inner join ConfigBundle:ConfigSociete s with s = r.societe
            where s = :soc and a.estSupprimer=0 ORDER BY a.created DESC"
        )
            ->setParameter('soc', $societe)
            ->getResult();
        return $tab;
    }
}
