<?php

namespace StockBundle\Repository;

/**
 * StockApprovisionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockApprovisionnementRepository extends \Doctrine\ORM\EntityRepository
{
    public function taille($societe)
    {
        $tab = $this->_em->createQuery(
            "select count(a)
            from StockBundle:StockArticle a
            inner join ConfigBundle:ConfigSociete s with s = a.societe
            where s = :soc"
        )
            ->setParameter('soc', $societe)
            ->getResult();
        return $tab[0][1];
    }
}
