<?php

namespace StockBundle\Repository;

/**
 * StockServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockServRepository extends \Doctrine\ORM\EntityRepository
{
}
