<?php

namespace AppBundle\Repository;

/**
 * SuperAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
