# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
#        FOS\UserBundle\Model\UserInterface: bcrypt
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_FNS_ADMIN:     ROLE_USER
        ROLE_CLT_ADMIN:     ROLE_USER
        ROLE_AGENT:         ROLE_USER
        ROLE_CAISSE:        ROLE_AGENT
        ROLE_VENDEUR:       ROLE_AGENT
        ROLE_COMPTABLE:     ROLE_AGENT
        ROLE_CONTROLEUR:      ROLE_AGENT
        ROLE_VISITEUR:      ROLE_AGENT
        ROLE_ADMIN:         [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                default_target_path: redirect_user

                csrf_token_generator: security.csrf.token_manager
                failure_path:   null
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }