<?php

namespace UserBundle\Repository;

/**
 * FosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosUserRepository extends \Doctrine\ORM\EntityRepository
{

    public function listeUsers($societe)
    {
        $tab = $this->_em->createQuery(
            "select u
            from UserBundle:FosUser u
            inner join ConfigBundle:ConfigAgence a with a = u.agence
            inner join ConfigBundle:ConfigSociete s with s = a.societe 
            where s = :soc and u.estSupprimer = :sup ORDER BY u.lastLogin DESC"
        )
            ->setParameter('soc', $societe)
            ->setParameter('sup', 0)
            ->getResult();
        return $tab;
    }

    public function listeAdminUsers()
    {
        $tab = $this->_em->createQuery(
            "select u
            from UserBundle:FosUser u ORDER BY u.lastLogin DESC "
        )
            ->getResult();
        return $tab;
    }

}
