<?php

namespace UserBundle\Repository;

/**
 * MouchardFichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouchardFichierRepository extends \Doctrine\ORM\EntityRepository
{
}
