<?php

namespace UserBundle\Repository;

/**
 * UserMouchardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMouchardRepository extends \Doctrine\ORM\EntityRepository
{
}
