<?php

namespace UserBundle\Repository;

/**
 * UserSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
