<?php

namespace UserBundle\Repository;

/**
 * UserAgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAgenceRepository extends \Doctrine\ORM\EntityRepository
{
}
