<?php

namespace TiersBundle\Repository;

/**
 * TiersTiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiersTiersRepository extends \Doctrine\ORM\EntityRepository
{
}
