<?php

namespace TiersBundle\Repository;

use UserBundle\Entity\FosUser;

/**
 * TiersFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiersFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function taille($societe)
    {
        $tab = $this->_em->createQuery(
            "select count(a)
            from StockBundle:StockArticle a
            inner join ConfigBundle:ConfigSociete s with s = a.societe
            where s = :soc"
        )
            ->setParameter('soc', $societe)
            ->getResult();
        return $tab[0][1];
    }


    public function listeFournisseurSoc($userID = null )
    {
        $societe = $this->_em->getRepository(FosUser::class)->find($userID)->getAgence()->getSociete();

        return $this
            ->createQueryBuilder('a')
            ->innerJoin('a.societe', 's')
            ->where('s = :societe')
            ->setParameter('societe', $societe);
    }

}
