<?php

namespace ConfigBundle\Repository;

/**
 * PaysLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigPaysLangRepository extends \Doctrine\ORM\EntityRepository
{

    public function listePays()
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.lang = 1');
    }
}
