<?php

namespace ConfigBundle\Repository;

/**
 * ConfigTypeFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigTypeFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
