<?php

namespace ConfigBundle\Repository;

use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\Query\Expr\Join;
use http\Client\Curl\User;
use UserBundle\Entity\FosUser;

/**
 * ConfigAgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigAgenceRepository extends \Doctrine\ORM\EntityRepository
{

    public function taille()
    {
        $tab = $this->_em->createQuery(
            "select count(a)
            from ConfigBundle:ConfigAgence a"
        )
            ->getResult();
        return $tab[0][1];
    }


    public function tailles($societe = null)
    {
        $whereSociete = $societe !== null ? 'where s=:soc' : '';
        $tab = $this->_em->createQuery(
            "select count(a)
            from ConfigBundle:ConfigAgence a
            inner join ConfigBundle:ConfigSociete s with s = a.societe
            {$whereSociete}"
        );
        if ($societe) {
            $tab->setParameter('soc', $societe);
        }
        $tab = $tab->getResult();

        return $tab[0][1];
    }


    public function listeAgenceSoc($userID = null)
    {
        if ($userID !== null)
            $societe = $this->_em->getRepository(FosUser::class)->find($userID)->getAgence()->getSociete();
        else
            $societe = null;

        return $this
            ->createQueryBuilder('a')
            ->innerJoin('a.societe', 's')
            ->where('s = :societe and a.estSupprimer =0 ')
            ->setParameter('societe', $societe);
    }


    public function listeAgenceActiveSoc($userID = null)
    {

        if ($userID !== null)
            $societe = $this->_em->getRepository(FosUser::class)->find($userID)->getAgence()->getSociete();
        else
            $societe = null;

        return $this
            ->createQueryBuilder('a')
            ->innerJoin('a.societe', 's')
            ->where('s = :societe and a.estActif = 1 and a.estSupprimer =0 ')
            ->setParameter('societe', $societe);
    }


}
