<?php

namespace ConfigBundle\Repository;

/**
 * ConfigAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigAbonnementRepository extends \Doctrine\ORM\EntityRepository
{

    public function listeAbonnementSansEssaie() {
        $val="Essaie IGO-FACTURATION";
        return $this->_em->createQuery(
            "select t.id, t.libelle
            from ConfigBundle:ConfigAbonnement t
            where t.libelle != :valeur
            and t.estSupprimer = 0 
            and t.estActif = 1 ORDER BY t.createdAt ASC"
        )->setParameter('valeur', $val)
            ->getResult();
    }


    public function listeAbonnementSansEssai($etaEsaaie)
    {
        if ($etaEsaaie)
        {
            $val="Essaie IGO-FACTURATION";

            return $this
                ->createQueryBuilder('a')
                ->where('a.libelle != :valeur and a.estActif = 1 and a.estSupprimer =0 ')
                ->setParameter('valeur', $val);
        } else
        {
            return $this
                ->createQueryBuilder('a')
                ->where('a.estActif = 1 and a.estSupprimer =0 ');
        }

    }


}
