<?php

namespace ConfigBundle\Repository;

use ConfigBundle\Entity\ConfigRaisonRejet;

/**
 * ConfigRaisonRejetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRaisonRejetRepository extends \Doctrine\ORM\EntityRepository
{

}
