<?php

namespace ConfigBundle\Repository;

/**
 * ConfigTypeGenerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigTypeGenerationRepository extends \Doctrine\ORM\EntityRepository
{
}
