<?php

namespace ConfigBundle\Repository;

/**
 * ConfigModeReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigModeReglementRepository extends \Doctrine\ORM\EntityRepository
{
}
