<?php

namespace ConfigBundle\Repository;

/**
 * ConfigTypeActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigTypeActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
