<?php

namespace ConfigBundle\Repository;

/**
 * ConfigDeviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigDeviseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getdevise()
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.id = 1');
    }
}
