<?php

namespace ConfigBundle\Repository;

/**
 * ConfigTauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigTauxRepository extends \Doctrine\ORM\EntityRepository
{
}
