<?php

namespace ConfigBundle\Repository;

/**
 * ConfigEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigEtatRepository extends \Doctrine\ORM\EntityRepository
{
}
