<?php

namespace ConfigBundle\Repository;

use ConfigBundle\Entity\ConfigSociete;

/**
 * ConfigAbonnementSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigAbonnementSocieteRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param ConfigSociete $societe
     *
     * @return bool
     */
    public function hasActifAbonnement(ConfigSociete $societe): bool {
        $abonnement = $this->_em->createQuery(
            "select a
            from ConfigBundle:ConfigAbonnementSociete a
            where a.societe = :societe
            and a.estActif = true
            and a.finAbonnement >= :now"
        )->setParameters([
            'societe' => $societe,
            'now' => new \DateTime()
        ])->getResult();
        return $abonnement !== [];
    }


}
