<?php

namespace ConfigBundle\Repository;

/**
 * LangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigLangRepository extends \Doctrine\ORM\EntityRepository
{
}
