<?php

namespace ConfigBundle\Repository;

/**
 * ConfigTaxeGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigTaxeGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
