<?php

namespace ConfigBundle\Repository;

/**
 * ConfigBanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigBanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
