<?php

namespace ConfigBundle\Repository;

/**
 * ZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
