<?php

namespace ConfigBundle\Repository;

/**
 * ConfigPaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigPaysRepository extends \Doctrine\ORM\EntityRepository
{
}
