<?php

namespace ConfigBundle\Repository;

/**
 * ConfigTypeGenerationSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigTypeGenerationSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
