<?php

namespace ConfigBundle\Repository;

/**
 * ConfigUniteMesureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigUniteMesureRepository extends \Doctrine\ORM\EntityRepository
{
}
