<?php

namespace ConfigBundle\Repository;

/**
 * ConfigModePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigModePaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
