<?php

namespace OperationsClientBundle\Repository;

/**
 * ClientFactureAvoirExportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFactureAvoirExportationRepository extends \Doctrine\ORM\EntityRepository
{
}
