<?php

namespace OperationsClientBundle\Repository;

/**
 * ClientDevisExportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientDevisExportationRepository extends \Doctrine\ORM\EntityRepository
{
}
