<?php

namespace OperationsClientBundle\Repository;

/**
 * ClientFactureReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFactureReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
