<?php

namespace OperationsClientBundle\Repository;
use ConfigBundle\Entity\ConfigSociete;

/**
 * ClientFactureAvoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFactureAvoirRepository extends \Doctrine\ORM\EntityRepository
{

}
