<?php

namespace OperationsClientBundle\Repository;

/**
 * ClientFactureDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFactureDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
