<?php

namespace OperationsClientBundle\Repository;

use ConfigBundle\Entity\ConfigAgence;
use ConfigBundle\Entity\ConfigSociete;
use OperationsClientBundle\Entity\ClientDevis;
use OperationsClientBundle\Entity\ClientFacture;
use OperationsClientBundle\Entity\ClientFactureDetail;

/**
 * ClientFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFactureRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEditInfo(ClientFacture $facture) {
        $devis = null;
        if ($facture->getId()) {
            $devis = $this->_em->getRepository(ClientDevis::class)->find($facture->getId());
        }
        return [
            'client' => $facture->getClient()->getNom(),
            'data_facture' => $facture->getDateFacture(),
            'data_reglement' => $devis ? $devis->getDateReglement() : new \DateTime(),
            'devise' => $facture->getDevise()->getId(),
            'tva' => $facture->getTauxTVA(),
            'totalHT' => $facture->getTotalHT(),
            'totalAIB' => $facture->getTotalAIB(),
            'totalTTC' => $facture->getTotalTTC(),
            'totalTVA' => $facture->getTotalTVA(),
            'details' => (static function() use ($facture) {
                $data = [];
                /** @var ClientFactureDetail $detail */
                foreach ($facture->getDetails() as $detail) {
                    $data[] = [
                        'produit' => $detail->getProduit()->getId(),
                        'uniteMesure' => $detail->getUniteMesure()->getId(),
                        'quantite' => $detail->getQuantite(),
                        'prixVenteUnitaire' => $detail->getPrixVenteUnitaire(),
                        'tauxRemise' => $detail->getTauxRemise(),
                        'aibDeductible' => $detail->getAibDeductible(),
                        'tauxAIB' => $detail->getTauxAIB(),
                        'description' => $detail->getDescription(),
                        'hasTaxeSpecifique' => $detail->getHasTaxeSpecifique(),
                        'taxeSpecifique' => $detail->getTaxeSpecifique(),
                        'descriptionTaxeSpecifique' => $detail->getDescriptionTaxeSpecifique(),
                        'changementPrixUnitaireTTC' => $detail->getChangementPrixUnitaireTTC(),
                        'dernierPrixOrigine' => $detail->getDernierPrixOrigine(),
                        'descriptionPrixOrigine' => $detail->getDescriptionPrixOrigine(),
                        'taxeDeSejour' => $detail->getTaxeDeSejour()
                    ];
                }
                return $data;
            })(),
        ];
    }

    public function taille($societe)
    {
        $tab = $this->_em->createQuery(
            "select count(a)
            from StockBundle:StockArticle a
            inner join ConfigBundle:ConfigSociete s with s = a.societe
            where s = :soc"
        )
            ->setParameter('soc', $societe)
            ->getResult();
        return $tab[0][1];
    }

//    public function getFacturesAvoirEtVente(ConfigAgence $agence, $codesFactures)
    public function getFacturesAvoirEtVente($codesFactures, $societe)
    {
        $qb = $this
            ->createQueryBuilder('f')
            ->leftJoin('f.typeFacture', 'tf')
//            ->where('f.agence = :agence')
//            ->setParameter('agence', $agence)
            ->andWhere('tf.code IN (:codesFactures) and f.societe = :soc')
            ->setParameter('codesFactures', $codesFactures)
            ->setParameter('soc', $societe)
            ->orderBy('f.dateFacture', 'desc');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getByFiltres($tempsFactureActif, $typeTemps, $tempsFacturation, $arrayTypesFacture, $arrayClients, $configSociete, $etatfactures)
    {
        $qb = $this
            ->createQueryBuilder('f')
            ->leftJoin('f.typeFacture', 'tf')
            ->andWhere("tf.code IN ('FV', 'EV', 'FA', 'EA')");

        if ($tempsFactureActif == 'true') {
            if ($typeTemps == 'date') {
                $qb->where("f.dateFacture = :dateFacturation")
                    ->setParameter('dateFacturation', $tempsFacturation);
            } elseif ($typeTemps == 'periode') {
                $tablePeriodeFinContrat = explode(' au ', $tempsFacturation);
                if (count($tablePeriodeFinContrat) == 2) {
                    $debut = new \DateTime(trim($tablePeriodeFinContrat[0], " \t\n\r\0\x0B\xC2\xA0"));
                    $fin = new \DateTime(trim($tablePeriodeFinContrat[1], " \t\n\r\0\x0B\xC2\xA0"));
                    $qb->andWhere('f.dateFacture >= :debut and f.dateFacture <= :fin')
                        ->setParameter('debut', $debut)
                        ->setParameter('fin', $fin);
                }
            }
        }

        if (!empty($arrayTypesFacture)) {
            $qb->andWhere('tf.id IN (:typesFactures)')
                ->setParameter('typesFactures', $arrayTypesFacture);
        }

        if (!empty($arrayClients)) {
            $qb->andWhere('f.client IN (:clients)')
                ->setParameter('clients', $arrayClients);
        }

        if (!empty($etatfactures)) {
            $qb->andWhere('f.etatDeclaration = (:etatFacture)')
                ->setParameter('etatFacture', $etatfactures);
        }

        $qb->andWhere('f.societe = (:soc)')
            ->setParameter('soc', $configSociete);

        $qb->orderBy('f.dateFacture', 'desc');

        return $qb
            ->getQuery()
            ->getResult();
    }


}
