<?php

namespace OperationsClientBundle\Repository;

/**
 * ClientFactureVenteExportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFactureVenteExportationRepository extends \Doctrine\ORM\EntityRepository
{
}
