<?php

namespace OperationsClientBundle\Repository;

/**
 * ClientPaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientPaiementRepository extends \Doctrine\ORM\EntityRepository
{


    public function liste($societe)
    {
        $tab = $this->_em->createQuery(
            "select a
            from OperationsClientBundle:ClientPaiement a
            inner join OperationsClientBundle:ClientFacture f with f = a.facture
            inner join ConfigBundle:ConfigSociete s with s = f.societe
            where s = :soc and a.supprimer = 0"
        )
            ->setParameter('soc', $societe)
            ->getResult();
        return $tab;
    }
}
