<?php

namespace OperationsClientBundle\Repository;

/**
 * ClientFactureDevisExportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientFactureDevisExportationRepository extends \Doctrine\ORM\EntityRepository
{
}
